// AUTO-GENERATED structural scaffold for the WomanRx shop. WomanRx-owned; no
// FormBlends dependency. Marketing copy is written fresh in the copy pass.

import type { Product, Category } from "./types";
import { COPY } from "./copy";

export const categories: Category[] = [
  {
    "slug": "glp1",
    "name": "GLP-1 Weight Loss",
    "description": "Clinically-backed GLP-1 receptor agonists for transformative weight management"
  },
  {
    "slug": "recovery",
    "name": "Recovery & Healing",
    "description": "Research on peptides for tissue repair and inflammation"
  },
  {
    "slug": "growth",
    "name": "Growth & Performance",
    "description": "Research on peptides for growth hormone and performance"
  },
  {
    "slug": "anti-aging",
    "name": "Anti-Aging & Longevity",
    "description": "Research on peptides for cellular health and longevity"
  },
  {
    "slug": "cognitive",
    "name": "Cognitive Enhancement",
    "description": "Research on peptides for cognitive function"
  },
  {
    "slug": "immune",
    "name": "Immune & Wellness",
    "description": "Research on peptides for immune function and wellness"
  },
  {
    "slug": "skin-hair",
    "name": "Skin & Hair",
    "description": "Research on peptides for skin and hair health"
  },
  {
    "slug": "sexual-wellness",
    "name": "Sexual Wellness",
    "description": "Research on peptides for sexual wellness"
  },
  {
    "slug": "gut-health",
    "name": "Gut Health",
    "description": "Research on peptides for gut health and microbiome"
  },
  {
    "slug": "bioregulators",
    "name": "Bioregulators",
    "description": "Research on short-chain bioregulatory peptides"
  },
  {
    "slug": "metabolic",
    "name": "Metabolic & Fat Loss",
    "description": "Research on peptides for metabolic function"
  },
  {
    "slug": "sleep-stress",
    "name": "Sleep & Stress",
    "description": "Research on peptides for sleep and stress management"
  },
  {
    "slug": "bundles",
    "name": "Peptide Bundles",
    "description": "Pre-built peptide blends and stack-style products that can be checked out together"
  }
];

// Structural scaffold (slugs, pricing, specs). Marketing copy is layered in from
// the hand-authored COPY overlay so regenerating this file never clobbers copy.
const RAW: Product[] = [
  {
    "slug": "semaglutide",
    "name": "Semaglutide",
    "category": "GLP-1 Weight Loss",
    "categorySlug": "glp1",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/semaglutide.webp",
    "price": 294,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.1%",
    "featured": true,
    "bestseller": true,
    "isGlp1": true,
    "originalPrice": 444,
    "badge": "Most Popular"
  },
  {
    "slug": "tirzepatide",
    "name": "Tirzepatide",
    "category": "GLP-1 Weight Loss",
    "categorySlug": "glp1",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/tirzepatide.webp",
    "price": 344,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.3%",
    "featured": true,
    "bestseller": true,
    "isGlp1": true,
    "originalPrice": 544,
    "badge": "Strongest Results"
  },
  {
    "slug": "liraglutide",
    "name": "Liraglutide",
    "category": "GLP-1 Weight Loss",
    "categorySlug": "glp1",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/liraglutide.webp",
    "price": 194,
    "unit": "3mg vial",
    "concentration": "3mg/vial",
    "purity": "98.9%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 294,
    "badge": "Best Value"
  },
  {
    "slug": "aod-9604",
    "name": "AOD-9604",
    "category": "Metabolic & Fat Loss",
    "categorySlug": "metabolic",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/aod-9604.webp",
    "price": 194,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "bpc-157",
    "name": "BPC-157",
    "category": "Recovery & Healing",
    "categorySlug": "recovery",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/bpc-157.webp",
    "price": 194,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.2%",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "badge": "Top Seller"
  },
  {
    "slug": "tb-500",
    "name": "TB-500 (Thymosin Beta-4)",
    "category": "Recovery & Healing",
    "categorySlug": "recovery",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/tb-500.webp",
    "price": 44,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.1%",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 64
  },
  {
    "slug": "bpc-157-tb-500-blend",
    "name": "BPC-157 / TB-500 Blend",
    "category": "Recovery & Healing",
    "categorySlug": "recovery",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/bpc-157-tb-500-blend.webp",
    "price": 244,
    "unit": "10mg vial (5mg each)",
    "concentration": "5mg BPC-157 + 5mg TB-500",
    "purity": "99.0%",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "badge": "Best Seller"
  },
  {
    "slug": "cjc-1295-ipamorelin",
    "name": "CJC-1295 / Ipamorelin Blend",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/cjc-1295-ipamorelin.webp",
    "price": 64,
    "unit": "5mg blend",
    "concentration": "2.5mg CJC + 2.5mg Ipamorelin",
    "purity": "99.1%",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 94
  },
  {
    "slug": "mk-677",
    "name": "MK-677 (Ibutamoren)",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/mk-677.webp",
    "price": 74,
    "unit": "25mg/mL (30mL)",
    "concentration": "25mg/mL",
    "purity": "99.4%",
    "featured": false,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 104
  },
  {
    "slug": "igf-1-lr3",
    "name": "IGF-1 LR3",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/igf-1-lr3.webp",
    "price": 114,
    "unit": "1mg vial",
    "concentration": "1mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 164
  },
  {
    "slug": "hexarelin",
    "name": "Hexarelin",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/hexarelin.webp",
    "price": 34,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.1%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 54
  },
  {
    "slug": "epithalon",
    "name": "Epithalon (Epitalon)",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/epithalon.webp",
    "price": 194,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.3%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "ghk-cu",
    "name": "GHK-Cu (Copper Peptide)",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ghk-cu.webp",
    "price": 174,
    "unit": "50mg vial",
    "concentration": "50mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "nad-plus",
    "name": "NAD+ Peptide Complex",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/nad-plus.webp",
    "price": 174,
    "unit": "500mg vial",
    "concentration": "500mg/vial",
    "purity": "99.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "semax",
    "name": "Semax",
    "category": "Cognitive Enhancement",
    "categorySlug": "cognitive",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/semax.webp",
    "price": 39,
    "unit": "30mg vial",
    "concentration": "30mg/vial",
    "purity": "99.2%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "selank",
    "name": "Selank",
    "category": "Cognitive Enhancement",
    "categorySlug": "cognitive",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/selank.webp",
    "price": 39,
    "unit": "30mg vial",
    "concentration": "30mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "dihexa",
    "name": "Dihexa",
    "category": "Cognitive Enhancement",
    "categorySlug": "cognitive",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/dihexa.webp",
    "price": 64,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.1%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 94
  },
  {
    "slug": "thymosin-alpha-1",
    "name": "Thymosin Alpha-1",
    "category": "Immune & Wellness",
    "categorySlug": "immune",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/thymosin-alpha-1.webp",
    "price": 244,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.2%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "ll-37",
    "name": "LL-37",
    "category": "Immune & Wellness",
    "categorySlug": "immune",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ll-37.webp",
    "price": 194,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "98.8%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "kpv",
    "name": "KPV",
    "category": "Immune & Wellness",
    "categorySlug": "immune",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/kpv.webp",
    "price": 39,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.1%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "ghk-cu-topical",
    "name": "GHK-Cu Topical Serum",
    "category": "Skin & Hair",
    "categorySlug": "skin-hair",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ghk-cu-topical.webp",
    "price": 74,
    "unit": "30mL bottle",
    "concentration": "3% GHK-Cu",
    "purity": "Pharmaceutical grade",
    "featured": false,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 114
  },
  {
    "slug": "melanotan-ii",
    "name": "Melanotan II",
    "category": "Skin & Hair",
    "categorySlug": "skin-hair",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/melanotan-ii.webp",
    "price": 24,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 39
  },
  {
    "slug": "pt-141",
    "name": "PT-141 (Bremelanotide)",
    "category": "Sexual Wellness",
    "categorySlug": "sexual-wellness",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/pt-141.webp",
    "price": 184,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.2%",
    "featured": false,
    "bestseller": true,
    "isGlp1": false
  },
  {
    "slug": "tadalafil-oxytocin-pt-141-nasal",
    "name": "Tadalafil/Oxytocin/PT-141 Nasal Spray",
    "category": "Sexual Wellness",
    "categorySlug": "sexual-wellness",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/tadalafil-oxytocin-pt-141-nasal.webp",
    "price": 174,
    "unit": "10mL nasal spray",
    "concentration": "50mg/600IU/2.5mg/mL",
    "purity": "Provider-reviewed",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "dsip",
    "name": "DSIP (Delta Sleep-Inducing Peptide)",
    "category": "Sleep & Stress",
    "categorySlug": "sleep-stress",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/dsip.webp",
    "price": 174,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "retatrutide",
    "name": "Retatrutide",
    "category": "GLP-1 Weight Loss",
    "categorySlug": "glp1",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/retatrutide.webp",
    "price": 384,
    "unit": "6mg vial",
    "concentration": "6mg/vial",
    "purity": "99.2%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 594,
    "badge": "Triple Agonist"
  },
  {
    "slug": "cagrilintide",
    "name": "Cagrilintide",
    "category": "Metabolic & Fat Loss",
    "categorySlug": "metabolic",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/cagrilintide.webp",
    "price": 274,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.1%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 394
  },
  {
    "slug": "tesofensine",
    "name": "Tesofensine",
    "category": "Metabolic & Fat Loss",
    "categorySlug": "metabolic",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/tesofensine.webp",
    "price": 74,
    "unit": "30 capsules",
    "concentration": "500mcg/capsule",
    "purity": "99.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 114
  },
  {
    "slug": "tb-500-fragment",
    "name": "TB-500 Fragment (Ac-SDKP)",
    "category": "Recovery & Healing",
    "categorySlug": "recovery",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/tb-500-fragment.webp",
    "price": 39,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.2%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "pentadecapeptide-bpc",
    "name": "BPC-157 Oral (Stable Arginate Salt)",
    "category": "Recovery & Healing",
    "categorySlug": "recovery",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/pentadecapeptide-bpc.webp",
    "price": 64,
    "unit": "60 capsules",
    "concentration": "500mcg/capsule",
    "purity": "99.1%",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 94,
    "badge": "Best Seller"
  },
  {
    "slug": "sermorelin",
    "name": "Sermorelin",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/sermorelin.webp",
    "price": 170,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.3%",
    "featured": false,
    "bestseller": true,
    "isGlp1": false
  },
  {
    "slug": "tesamorelin",
    "name": "Tesamorelin",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/tesamorelin.webp",
    "price": 244,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.4%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "badge": "FDA History"
  },
  {
    "slug": "ghrp-2",
    "name": "GHRP-2",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ghrp-2.webp",
    "price": 27,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.2%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 44
  },
  {
    "slug": "ghrp-6",
    "name": "GHRP-6",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ghrp-6.webp",
    "price": 24,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 39
  },
  {
    "slug": "cjc-1295-dac",
    "name": "CJC-1295 DAC",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/cjc-1295-dac.webp",
    "price": 37,
    "unit": "2mg vial",
    "concentration": "2mg/vial",
    "purity": "99.1%",
    "featured": false,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "follistatin-344",
    "name": "Follistatin 344",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/follistatin-344.webp",
    "price": 144,
    "unit": "1mg vial",
    "concentration": "1mg/vial",
    "purity": "98.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 224
  },
  {
    "slug": "igf-1-des",
    "name": "IGF-1 DES (1-3)",
    "category": "Growth & Performance",
    "categorySlug": "growth",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/igf-1-des.webp",
    "price": 84,
    "unit": "1mg vial",
    "concentration": "1mg/vial",
    "purity": "98.8%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 134
  },
  {
    "slug": "foxo4-dri",
    "name": "FOXO4-DRI",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/foxo4-dri.webp",
    "price": 184,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "98.5%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 284,
    "badge": "Senolytic"
  },
  {
    "slug": "ss-31",
    "name": "SS-31 (Elamipretide)",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ss-31.webp",
    "price": 74,
    "unit": "25mg vial",
    "concentration": "25mg/vial",
    "purity": "99.3%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 124
  },
  {
    "slug": "humanin",
    "name": "Humanin",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/humanin.webp",
    "price": 64,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 94
  },
  {
    "slug": "5-amino-1mq",
    "name": "5-Amino-1MQ",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/5-amino-1mq.webp",
    "price": 84,
    "unit": "60 capsules",
    "concentration": "100mg/capsule",
    "purity": "99.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 124
  },
  {
    "slug": "n-acetyl-semax-amidate",
    "name": "N-Acetyl Semax Amidate (NASA)",
    "category": "Cognitive Enhancement",
    "categorySlug": "cognitive",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/n-acetyl-semax-amidate.webp",
    "price": 44,
    "unit": "30mg vial (nasal)",
    "concentration": "30mg/vial",
    "purity": "99.2%",
    "featured": false,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 69
  },
  {
    "slug": "n-acetyl-selank-amidate",
    "name": "N-Acetyl Selank Amidate",
    "category": "Cognitive Enhancement",
    "categorySlug": "cognitive",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/n-acetyl-selank-amidate.webp",
    "price": 39,
    "unit": "10mg vial (nasal)",
    "concentration": "10mg/vial",
    "purity": "99.1%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "p21",
    "name": "P21 (P021)",
    "category": "Cognitive Enhancement",
    "categorySlug": "cognitive",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/p21.webp",
    "price": 49,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 74
  },
  {
    "slug": "ta1-thymalin",
    "name": "Thymalin",
    "category": "Immune & Wellness",
    "categorySlug": "immune",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ta1-thymalin.webp",
    "price": 44,
    "unit": "20mg vial",
    "concentration": "20mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 69
  },
  {
    "slug": "vip",
    "name": "VIP (Vasoactive Intestinal Peptide)",
    "category": "Immune & Wellness",
    "categorySlug": "immune",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/vip.webp",
    "price": 54,
    "unit": "6mg vial",
    "concentration": "6mg/vial",
    "purity": "99.1%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 84
  },
  {
    "slug": "copper-peptide-ahk-cu",
    "name": "AHK-Cu (Copper Tripeptide)",
    "category": "Skin & Hair",
    "categorySlug": "skin-hair",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/copper-peptide-ahk-cu.webp",
    "price": 34,
    "unit": "200mg topical",
    "concentration": "200mg/bottle",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 54
  },
  {
    "slug": "snap-8",
    "name": "SNAP-8 (Acetyl Octapeptide-3)",
    "category": "Skin & Hair",
    "categorySlug": "skin-hair",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/snap-8.webp",
    "price": 29,
    "unit": "200mg topical",
    "concentration": "200mg/bottle",
    "purity": "99.3%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 44
  },
  {
    "slug": "matrixyl",
    "name": "Matrixyl (Palmitoyl Pentapeptide-4)",
    "category": "Skin & Hair",
    "categorySlug": "skin-hair",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/matrixyl.webp",
    "price": 24,
    "unit": "200mg topical",
    "concentration": "200mg/bottle",
    "purity": "99.2%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 39
  },
  {
    "slug": "kisspeptin-10",
    "name": "Kisspeptin-10",
    "category": "Sexual Wellness",
    "categorySlug": "sexual-wellness",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/kisspeptin-10.webp",
    "price": 44,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 69
  },
  {
    "slug": "gonadorelin",
    "name": "Gonadorelin (GnRH)",
    "category": "Sexual Wellness",
    "categorySlug": "sexual-wellness",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/gonadorelin.webp",
    "price": 94,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.3%",
    "featured": false,
    "bestseller": true,
    "isGlp1": false
  },
  {
    "slug": "oxytocin",
    "name": "Oxytocin",
    "category": "Sexual Wellness",
    "categorySlug": "sexual-wellness",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/oxytocin.webp",
    "price": 39,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "larazotide",
    "name": "Larazotide Acetate",
    "category": "Gut Health",
    "categorySlug": "gut-health",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/larazotide.webp",
    "price": 49,
    "unit": "60 capsules",
    "concentration": "500mcg/capsule",
    "purity": "99.3%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 74,
    "badge": "Phase 3 Trials"
  },
  {
    "slug": "bpc-157-kpv-blend",
    "name": "Gut Repair Blend (BPC-157 + KPV)",
    "category": "Gut Health",
    "categorySlug": "gut-health",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/bpc-157-kpv-blend.webp",
    "price": 74,
    "unit": "60 capsules",
    "concentration": "BPC 500mcg + KPV 500mcg per cap",
    "purity": "99.0%",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 114,
    "badge": "Best Seller"
  },
  {
    "slug": "epithalamin",
    "name": "Epithalamin (Epithalon Bioregulator)",
    "category": "Bioregulators",
    "categorySlug": "bioregulators",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/epithalamin.webp",
    "price": 34,
    "unit": "20mg vial",
    "concentration": "20mg/vial",
    "purity": "99.0%",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 54
  },
  {
    "slug": "pinealon",
    "name": "Pinealon",
    "category": "Bioregulators",
    "categorySlug": "bioregulators",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/pinealon.webp",
    "price": 29,
    "unit": "20mg vial",
    "concentration": "20mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 44
  },
  {
    "slug": "vesilute",
    "name": "Vesilute",
    "category": "Bioregulators",
    "categorySlug": "bioregulators",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/vesilute.webp",
    "price": 24,
    "unit": "20mg vial",
    "concentration": "20mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 39
  },
  {
    "slug": "adipotide",
    "name": "Adipotide (FTPP)",
    "category": "Metabolic & Fat Loss",
    "categorySlug": "metabolic",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/adipotide.webp",
    "price": 64,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "98.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 94
  },
  {
    "slug": "aicar",
    "name": "AICAR",
    "category": "Metabolic & Fat Loss",
    "categorySlug": "metabolic",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/aicar.webp",
    "price": 64,
    "unit": "50mg vial",
    "concentration": "50mg/vial",
    "purity": "99.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 94
  },
  {
    "slug": "fragment-176-191",
    "name": "HGH Fragment 176-191",
    "category": "Metabolic & Fat Loss",
    "categorySlug": "metabolic",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/fragment-176-191.webp",
    "price": 39,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 59
  },
  {
    "slug": "epitalon",
    "name": "Epitalon (Epithalon Injectable)",
    "category": "Sleep & Stress",
    "categorySlug": "sleep-stress",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/epitalon.webp",
    "price": 39,
    "unit": "10mg vial",
    "concentration": "10mg/vial",
    "purity": "99.2%",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "originalPrice": 59,
    "badge": "Sleep + Longevity"
  },
  {
    "slug": "selank-nasal",
    "name": "Selank Nasal Spray",
    "category": "Sleep & Stress",
    "categorySlug": "sleep-stress",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/selank-nasal.webp",
    "price": 124,
    "unit": "15mL nasal spray",
    "concentration": "0.15% solution",
    "purity": "99.1%",
    "featured": false,
    "bestseller": true,
    "isGlp1": false
  },
  {
    "slug": "ghk",
    "name": "GHK (Glycyl-L-Histidyl-L-Lysine)",
    "category": "Recovery & Healing",
    "categorySlug": "recovery",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ghk.webp",
    "price": 24,
    "unit": "200mg vial",
    "concentration": "200mg/vial",
    "purity": "99.3%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 39
  },
  {
    "slug": "ace-031",
    "name": "ACE-031",
    "category": "Immune & Wellness",
    "categorySlug": "immune",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ace-031.webp",
    "price": 114,
    "unit": "1mg vial",
    "concentration": "1mg/vial",
    "purity": "98.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "originalPrice": 174
  },
  {
    "slug": "nad-nasal",
    "name": "NAD+ Nasal Spray",
    "category": "Anti-Aging & Longevity",
    "categorySlug": "anti-aging",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/nad-nasal.webp",
    "price": 144,
    "unit": "15mL nasal spray",
    "concentration": "100mg/ml",
    "purity": "99.5%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "mots-c",
    "name": "MOTS-c",
    "category": "Metabolic & Fat Loss",
    "categorySlug": "metabolic",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/mots-c.webp",
    "price": 244,
    "unit": "5mg vial",
    "concentration": "5mg/vial",
    "purity": "99.0%",
    "featured": false,
    "bestseller": false,
    "isGlp1": false
  },
  {
    "slug": "glutathione-injectable",
    "name": "Glutathione Injectable",
    "category": "Immune & Wellness",
    "categorySlug": "immune",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/glutathione-injectable.webp",
    "price": 94,
    "unit": "10mL vial",
    "concentration": "Glutathione",
    "purity": "Provider reviewed",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "badge": "Antioxidant"
  },
  {
    "slug": "semax-nasal-spray",
    "name": "Semax Nasal Spray",
    "category": "Cognitive Enhancement",
    "categorySlug": "cognitive",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/semax-nasal-spray.webp",
    "price": 124,
    "unit": "20mL nasal spray",
    "concentration": "Semax 2.5mg/mL",
    "purity": "Provider reviewed",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "badge": "Nasal Spray"
  },
  {
    "slug": "bpc-157-kpv-tb-500-blend",
    "name": "BPC-157 / KPV / TB-500 Blend",
    "category": "Peptide Bundles",
    "categorySlug": "bundles",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/bpc-157-kpv-tb-500-blend.webp",
    "price": 274,
    "unit": "5mL vial",
    "concentration": "BPC-157 / KPV / TB-500",
    "purity": "Provider reviewed",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "badge": "Recovery Blend"
  },
  {
    "slug": "premium-recovery-quad-stack",
    "name": "Premium Recovery Quad Stack",
    "category": "Peptide Bundles",
    "categorySlug": "bundles",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/premium-recovery-quad-stack.webp",
    "price": 344,
    "unit": "5mL vial",
    "concentration": "BPC-157 / GHK-Cu / KPV / TB-500",
    "purity": "Provider reviewed",
    "featured": true,
    "bestseller": true,
    "isGlp1": false,
    "badge": "Premium"
  },
  {
    "slug": "tesamorelin-ipamorelin-blend",
    "name": "Tesamorelin / Ipamorelin Blend",
    "category": "Peptide Bundles",
    "categorySlug": "bundles",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/tesamorelin-ipamorelin-blend.webp",
    "price": 294,
    "unit": "5mL vial",
    "concentration": "Tesamorelin / Ipamorelin",
    "purity": "Provider reviewed",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "badge": "GH Blend"
  },
  {
    "slug": "ghk-cu-epithalon-blend",
    "name": "GHK-Cu / Epithalon Blend",
    "category": "Peptide Bundles",
    "categorySlug": "bundles",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/ghk-cu-epithalon-blend.webp",
    "price": 274,
    "unit": "5mL vial",
    "concentration": "GHK-Cu / Epithalon",
    "purity": "Provider reviewed",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "badge": "Longevity Blend"
  },
  {
    "slug": "mots-c-tesamorelin-blend",
    "name": "MOTS-C / Tesamorelin Blend",
    "category": "Peptide Bundles",
    "categorySlug": "bundles",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/mots-c-tesamorelin-blend.webp",
    "price": 344,
    "unit": "5mL vial",
    "concentration": "MOTS-C / Tesamorelin",
    "purity": "Provider reviewed",
    "featured": true,
    "bestseller": false,
    "isGlp1": false,
    "badge": "Metabolic Stack"
  },
  {
    "slug": "semax-selank-blend",
    "name": "Semax / Selank Blend",
    "category": "Peptide Bundles",
    "categorySlug": "bundles",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/semax-selank-blend.webp",
    "price": 224,
    "unit": "5mL vial",
    "concentration": "Semax / Selank",
    "purity": "Provider reviewed",
    "featured": false,
    "bestseller": true,
    "isGlp1": false,
    "badge": "Focus Blend"
  },
  {
    "slug": "sleep-recovery-stack",
    "name": "Sleep + Recovery Stack",
    "category": "Peptide Bundles",
    "categorySlug": "bundles",
    "tagline": "",
    "description": "",
    "longDescription": "",
    "benefits": [],
    "scienceNotes": "",
    "image": "/images/shop/sleep-recovery-stack.webp",
    "price": 294,
    "unit": "5mL vial",
    "concentration": "DSIP / BPC-157 / CJC",
    "purity": "Provider reviewed",
    "featured": false,
    "bestseller": false,
    "isGlp1": false,
    "badge": "Sleep Stack"
  }
];

export const products: Product[] = RAW.map((p) => {
  const c = COPY[p.slug];
  return c ? { ...p, ...c } : p;
});

export const getProductBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);
export const getProductsByCategory = (categorySlug: string): Product[] =>
  products.filter((p) => p.categorySlug === categorySlug);
export const getFeaturedProducts = (): Product[] => products.filter((p) => p.featured);
export const getBestsellers = (): Product[] => products.filter((p) => p.bestseller);
export const getGlp1Products = (): Product[] => products.filter((p) => p.isGlp1);
